version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm run build
      - run: npm run test:mocha
      - run:
          name: install nvm
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
            echo "source ~/.nvm/nvm.sh --no-use" >> $BASH_ENV
      - run: nvm install 6 && nvm use 6 && npm run test:mocha
      - run: rm -rf dist/__specs__
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - persist_to_workspace:
          root: ~/project
          paths: 
            - .npmrc
            - dist
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: npm publish
  deploy-beta:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: npm publish --tag beta

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /release-[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
      - deploy-beta:
          requires:
            - build
          filters:
            tags:
              only: /beta-[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
